services:
  db:
    image: postgres:17
    container_name: eqsitecms-${EQUESTRIAN_NAME}-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
    expose:
      - 5432
    ports:
      - "${EXPOSE_DB_PORT}:5432"
    volumes:
      - ./${EQUESTRIAN_NAME}-pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eqsitecms-${EQUESTRIAN_NAME}-app
    restart: always
    environment:
      DEBUG: ${DEBUG}
      SWAGGER_TITLE: ${SWAGGER_TITLE}
      WORKERS: ${WORKERS}
      SECRET_KEY: ${SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRES_IN_MINUTES: ${ACCESS_TOKEN_EXPIRES_IN_MINUTES}
      REFRESH_TOKEN_EXPIRES_IN_DAYS: ${REFRESH_TOKEN_EXPIRES_IN_DAYS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      CMS_PANEL_DOMAIN: ${CMS_PANEL_DOMAIN}
      CMS_BACKEND_DOMAIN: ${CMS_BACKEND_DOMAIN}
      MAIN_SITE_DOMAIN: ${MAIN_SITE_DOMAIN}      
    depends_on:
      - db
    ports:
      - "${EXPOSE_APP_PORT}:8000"
    volumes:
      - ./src:/eqsitecms/src
    working_dir: /eqsitecms
